### ISSUE TITLE
Provide a Profiles/sample yaml file with typical values filled in?

### ISSUE THREAD

**Issue by tgogos** [EVOLVED-5G/TSN_FrontEnd#7]
Hey @NaniteBased , Tasos here! Can you share the following with some typical values to use while we start playing around with this component? Thanks in advance!

```yaml
# Profiles must be saved as yml or yaml files.

# The following values specify the expected (SLA) KPIs
delay: <float (ms). Maximum value>
jitter: <float (ms). Maximum value>
throughput: <float (Mbps). Minimum value>
packet_loss: <float (percent). Maximum value>

# The following values specify the traffic type:
periodicity: <'periodic' or 'sporadic'>
period: <float (ms)>
data_size: <integer (bytes)>
critical: <boolean>
```

**Comment by NaniteBased** [comment]
Hi @tgogos, there are no sample profiles because, without a back-end available, the front-end will automatically reject any request (other than 'best-effort'), given that it cannot configure anything in the network on its own. We cannot provide a back-end either, because these need to be custom made for each testbed, and, in turn, would dictate which values you can use for each of the parameters in the profiles.

But regardless of this, I can share the profiles I'm using for testing:

**periodic.yml:**
```yaml
# The following values specify the expected (SLA) KPIs
delay: 50.0
jitter: 10.0
throughput: 0.04
packet_loss: 5.0

# The following values specify the traffic type:
periodicity: sporadic
period: 50.0
data_size: 200.0
critical: True
```

**sporadic.yml:**
```yaml
# The following values specify the expected (SLA) KPIs
delay: 15.0
jitter: 3.5
throughput: 0.29
packet_loss: 1.0

# The following values specify the traffic type:
periodicity: periodic
period: 15.0
data_size: 500.0
critical: True
```

Even if you cannot apply them they should at least appear when listing the available profiles and inspecting their details.
